
# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js

runtime:
  nodePool: default

node_js:
  - 8.2.1

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

build:
  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    - echo "foo"
   
jobs:
  - name: runSh-Job-Ubuntu-14
    type: runSh
    runtime:
      nodePool: default
    steps:
      - TASK:
          script: 
            - echo "foo"
         
