
# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js

runtime:
  nodePool: default

node_js:
  - 8.2.1

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

build:
  # http://docs.shippable.com/ci/shippableyml/#ci
  pre_ci_boot:
    image_name: zephyrprojectrtos/ci
    image_tag: v0.3
    pull: true
    options: "-e HOME=/home/buildslave"
  pre_ci:
    - shipctl get_resource_id testGrisham_ciRepo
  ci:
    - echo $SHIPPABLE_BUILD_DIR
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    - ls -al $SHIPPABLE_BUILD_DIR
  push:
    - shipctl get_resource_id testGrisham_ciRepo

resources:
  - name: resource-state
    type: state
jobs:
  - name: runSh-Job-Ubuntu-14
    type: runSh
    runtime:
      nodePool: default
    steps:
      - IN: resource-state
      - TASK:
          runtime:
            options:
              imageName: zephyrprojectrtos/ci
              imageTag: v0.3
              pull: true
              options: "-e HOME=/home/buildslave"
          script: 
            - echo "foo"
            - shipctl get_resource_id resource-state
            - sleep 150

  - name: runSh-Job-Ubuntu-16
    type: runSh
    runtime:
      nodePool: default-16
    steps:
      - IN: resource-state
      - TASK:
          runtime:
            options:
              imageName: zephyrprojectrtos/ci
              imageTag: v0.3
              pull: true
              options: "-e HOME=/home/buildslave"
          script: 
            - echo "foo"
            - shipctl get_resource_id resource-state
            - sleep 150

  - name: runSh-Job-Centos
    type: runSh
    runtime:
      nodePool: default-centos
    steps:
      - IN: resource-state
      - TASK:
          runtime:
            options:
              imageName: zephyrprojectrtos/ci
              imageTag: v0.3
              pull: true
              options: "-e HOME=/home/buildslave"
          script: 
            - echo "foo"
            - shipctl get_resource_id resource-state
            - sleep 150

  - name: runSh-Job-Ubuntu-aarch64
    type: runSh
    runtime:
      nodePool: default-aarch
    steps:
      - IN: resource-state
      - TASK:
          runtime:
            options:
              imageName: drydockaarch64/u16
              imageTag: v5.10.4
              pull: true
          script: 
            - echo "foo"
            - shipctl get_resource_id resource-state
            - sleep 150
